### ISSUE TITLE
seismic movies

### ISSUE THREAD

**Issue by lheagy** [ubcgif/gpg#118]
I have hacked together a solution to get the videos on youtube... 

There are 2: one for the [slow layer over a fast layer](https://www.youtube.com/watch?v=0z2WTLLKjGY), and one for a [fast layer over a slow layer](https://www.youtube.com/watch?v=eI3epl0ek3g). The rst to embed is shown below. You can re-size the videos by equally adjusting the width and height

slow layer over a fast layer
```
.. raw:: html

    <div style="margin-top:10px; margin-bottom:20px;" align="center">
    <iframe width="560" height="315" src="https://www.youtube.com/embed/0z2WTLLKjGY?rel=0" frameborder="0" allowfullscreen>
    </iframe>
    </div> 
```

fast layer over a slow layer 
```
.. raw:: html
    
    <div style="margin-top:10px; margin-bottom:20px;" align="center">
    <iframe width="560" height="315" src="https://www.youtube.com/embed/eI3epl0ek3g?rel=0" frameborder="0" allowfullscreen>
    </iframe>
    </div>
```

cc @dougoldenburg

**Comment by Pbellive** [comment]
Getting started on getting these movies and the apps integrated into GPG. Just pushed more restructuring to seismic-restructuring branch.

**Comment by Pbellive** [comment]
Movies are up, along with a couple from IRIS.
