### ISSUE TITLE
GPR refactor: Overview comments

### ISSUE THREAD

**Issue by lheagy** [ubcgif/gpg#125]
@dccowan : this is looking good. I have done a once-over and would be happy to read through in more detail when you consider this to be finalized. Below are some comments regarding the overall layout. See what you think, and please let me know if anything is unclear. cc @dougoldenburg 
- tests are currently failing and will need to be resolved: https://travis-ci.org/ubcgif/gpg/builds/166925337
![image](https://cloud.githubusercontent.com/assets/6361812/19337112/bae9b6e2-90c6-11e6-85b8-cb7963f3e039.png)
- could you please add links from the GPR index page back to electrical conductivity, magnetic permeability and dielectric permittivity in the "Physical Properties" chapter
- please run a spell check on the new content (if you are using sublime text view --> spell check)
![image](https://cloud.githubusercontent.com/assets/6361812/19337425/f2f2591a-90c9-11e6-8af6-e5fa731941fd.png)
- **Basic Principles** is quite long. Similar to Seismic, I would suggest breaking it up into several smaller pages. Perhaps:
    - Waves: includes Wave Velocity, Attenuation, Skin Depth, Wave Fronts and Ray Paths, geometric spreading  
    - Waves at interfaces (or Waves in earth materials): Reflection and Transmission of Radiowaves, Reflection at conductive object boundaries, refraction of radiowaves, scattering, 
    - Travel Times: includes the two layer earth example
- I am assuming the "GPR concepts" page will be removed?

**Comment by dccowan** [comment]
1) Broken hyperlink should be fixed.
2) Ran spell check to fix typos and looked for grammatical errors.
3) Links to physical property pages have been added.
4) GPR concepts and examples page was removed and old .html files were cleaned up.
5) I like keeping basic principles as is. The drop-down menu on the right shows the page layout.
