### ISSUE TITLE
Failed Travis test due to unrelated link

### ISSUE THREAD

**Issue by dccowan** [ubcgif/gpg#136]
There is a broken link in an unrelated section. As a result Travis fails and I cannot merge changes into master. Yes I did pull latest version of master.

/home/travis/build/ubcgif/gpg/content/gravity/gravity_gradients.rst:152: WARNING: broken link: http://www.eos.ubc.ca/courses/eosc350/content/methods/meth_4/assets/gravgrad-figs.pdf

**Comment by lheagy** [comment]
Can you please replace that link with: 

https://www.eoas.ubc.ca/courses/eosc350/content/methods/meth_4/assets/gravgrad-figs.pdf

(the eos --> eoas). EOS changed their websites and the re-direct is likely causing it to fail.

**Comment by dccowan** [comment]
I replaced the links to have `eoas` when appropriate in the file and it
still failed. It looked as though the link at the bottom of
gravity_gradients.rst was getting called to a line which was commented out.
I have tried quite a few things and Travis still fails. There is something
about syntax I am likely missing.

Devin
