### ISSUE TITLE
Magnetic Dipole section, Figure 1

### ISSUE THREAD

**Issue by micmitch** [ubcgif/gpg#23]
Concerning the first figure under the following section:

http://gpg.geosci.xyz/en/latest/content/magnetics/magnetics_buried_dipole.html#fields-due-to-a-magnetic-dipole

Do we want to define \Delta B and discuss the difference between \Delta B and B_t?

This could be done above the figure or in the missing figure caption.

**Comment by lheagy** [comment]
Yes, that would be good!
