### ISSUE TITLE
Dipole direction

### ISSUE THREAD

**Issue by micmitch** [ubcgif/gpg#26]
I was pretty sure that the dipole moment extends from the negative(south) pole to the positive(north) pole. The text at the end of the 

file:///C:/Users/micmitch/Documents/UBC/GIF/GPG/_build/html/content/magnetics/magnetics_extended_bodies.html#approximating-targets-using-magnetic-charges

section states that  "The direction of the dipole goes from the positive to negative charge"

Just like to confirm that this is wrong before I change it.

**Comment by dougoldenburg** [comment]
The text is correct.

**Comment by micmitch** [comment]
I think that we must be interpreting this differently.

**Comment by dougoldenburg** [comment]
Hi Michael,

                Can you drop up?

Doug

**Comment by micmitch** [comment]
Discussed with Doug and closed.
