### ISSUE TITLE
Incomplete sentence?

### ISSUE THREAD

**Issue by thast** [ubcgif/gpg#33]
http://gpg.geosci.xyz/en/latest/content/seismic/reflection/seismic_reflection_seismogram.html

Part of the sentence seems to miss, or brackets are unnecessary: 

"Compute the acoustic impedance as a function of depth. In practice, (combine density and velocity logs to do this.)"

**Comment by lheagy** [comment]
Good catch! 

I would suggest:

"Compute the acoustic impedance as a function of depth by taking the product of the density and velocity logs"

Thoughts @sgkang ??

**Comment by sgkang** [comment]
I like that @lheagy

**Comment by thast** [comment]
Good for me. I will put it.
