### ISSUE TITLE
function to move all contents of image folders

### ISSUE THREAD

**Issue by lheagy** [ubcgif/gpg#4]
to ensure all images are moved over each time, can we include a script that just grabs all of the contents of every folder labelled "images"?

**Comment by rowanc1** [comment]
I would suggest this being done at the end of the conf.py file. First, write a stand alone python script that moves the images that you need.

Add2Build.py
```python
import os

def moveImages():
   logic

if __name__ == "__main__":
    moveImages()
```

and then in the conf.py file (at the bottom):

```python

# ... conf.py

import Add2Build
Add2Build.moveImages()
```

**Comment by lheagy** [comment]
Thanks @rowanc1. See Add2Build.py!
