### ISSUE TITLE
Physical Properties - Mag 

### ISSUE THREAD

**Issue by lheagy** [ubcgif/gpg#60]
From @dougoldenburg in https://github.com/ubcgif/gpg/commit/306447eff8974f5f35e8d9acf19bb0c6d6cf8913

"I've replaced some of the material from the gpg that was omitted. I think the interactive graphic display is effective and we should keep it. The susceptibility graph that you made is informative but so too is the plot that was omitted (adapted from Clark and Emerson). Although there is overlap of certain items, there is some additional information. Let's put both in for now.  There is an inconsistency about hematite on the two plots.
For magnetic properties of soils some of the statements in the old gpg are relevant and maybe should be included some where. Also, the magnetic susceptibility of rocks often depends upon the % of magnetite. More information about this might be included.

@dougoldenburg : could you break this into a few todo's on specific pages?

**Comment by dccowan** [comment]
The hematites seem to line up fine on both figures. The value in the table below is within range. There is also a difference between SD and MD hematite grains and massive hematite-bearing rocks. I think I addressed all the necessary changes after the meeting.

**Comment by lheagy** [comment]
@dccowan : if changes have been made that address this, could you reference the pull request where the changes have been made and close this issue? Thanks!
