### ISSUE TITLE
Magnetic Surveying on GPG:    Introduction

### ISSUE THREAD

**Issue by dougoldenburg** [ubcgif/gpg#72]
As a first pass to restructuring this, I suggest the following:

(a) Motivational examples.
      (we can use the three in the slides:  geologic mapping,  inversion for a  mineral deposit, UXO)

(b) Slide 14 from lectures.. (this is a generic slide used for all of our surveys; but here we explicitly have magnetic susceptibility as the physical property.

(c) Statement as to what magnetic surveying is. Replace the current text with the summary paragraph in Foundations/Surveys/Magnetics. That is much better than what is currently written.

(d) Keep the annotated figures that are currently in the Introduction. They are a nice visual summary about the basic method and also they tie in with Slide 14.

**Comment by lheagy** [comment]
@fourndo : could you take a look at the issue list and close the mag ones that have been addressed (if you have the pr number, could you include that in the "close and comment"). Thanks!

**Comment by fourndo** [comment]
Done on PR #83
