### ISSUE TITLE
Magnetic Surveying on GPG:   Basic Principles

### ISSUE THREAD

**Issue by dougoldenburg** [ubcgif/gpg#74]
The basic thread for magnetic surveying is Slide 22 (sorry, I can't seem to get monosnap to copy the image here).  Maybe this works.
![magneticbasics_page_022](https://cloud.githubusercontent.com/assets/8864444/18237230/c2acdfea-72e3-11e6-816c-354ad7ec7315.jpg)

Source: Earth's field  (slides 15 to 20; or equivalent)  + material in the current GPG (There is some good material in the GPG but it is very disorganized compared to what we want for our current structure.)
Main items
       going from dynamo to earth's field as it interacts with solar wind
       Earth's field at the surface, H,D,I;   some maps;   IGRF 
        

Magnetizing the rocks
       Magnetization or rocks (possibly links to Phys Prop section)
       Dipole moment (volume integrated magnetization) 
       Introduce the app here

Fields
       Anomalous fields are vectors
       Measure components (projection onto a particular direction; x,y,z or earth's field
       App examples (how same body buried at different locations in the earth yields different signatures)

       Things get more complicated because the anomalous field we are trying to measure is buried in the earth's field.  
       Subtract the IGRF
       Interpreting the result (particularly TMI and showing that it is project of the anomalous field onto the earth's field.

??? on looking at this we may choose to re-write the basic slide slightly. For now, combining the flow of the slides and the existing material on the GPG into the above framework takes us a lot closer to an end goal.

**Comment by fourndo** [comment]
Partially done on PR #84
