### ISSUE TITLE
Magnetic Surveying on GPG:   

### ISSUE THREAD

**Issue by dougoldenburg** [ubcgif/gpg#75]
1. Basic Principles of Survey Design
     area of data acquisition must be large enough to capture the anomaly
     sampling interval must be sufficiently fine (for a dipole at least 3 points per half-width  
             relationship between halfwidth and depth of burial for a dipole
  
Use Applet examples and buried prism to get these points across. In addition we could put together a list of some specific things they could do with the app to gain insight. 

In general, we want to use a numerical modelling package to simulate the expected response and use that to help determine sampling strategy.  
     Again, we can provide a list of things they might explore (sheets, elongated bodies, small object at depth etc.);

2. Instrumentation (some background in GPG is good)
     Options:   total field magnetometers (proton precesson, Cesium vapor)
                     magnetometers (fluxgate)
                     ganged systems like that for UXO
                     borehole magnetometers

3.  Field acquisition:
       Generally collect data  in lines (particularly airborne data)
        On ground line spacing is ideally same as station spacing
        Need a base-station

Comment:  Instrumentation could come first but from the viewpoint of understanding the survey, and the fact that we are following from Basic Physics, having it in #2 position works

**Comment by fourndo** [comment]
Done on PR #91
