### ISSUE TITLE
Magnetic Surveying on GPG:   Data

### ISSUE THREAD

**Issue by dougoldenburg** [ubcgif/gpg#76]
In this section we present a summary about the different types of magnetic data.   (maybe with a screen shot of a body and the associated field)

1. Total field data 
2. Total field anomaly
3. Magnetic field data 
4. Magnetic field anomaly data
5. (eventually: magnetic field in a borehole and issues wrt orientation)

**Comment by fourndo** [comment]
Done on PR #95
