### ISSUE TITLE
Magnetic Surveying on GPG:   Interpretation 

### ISSUE THREAD

**Issue by dougoldenburg** [ubcgif/gpg#77]
Comment: The flow outlined in the slides is good.

1. Inferences from data maps 
          Comparison of processed data with geology sections

2. Interpret with a simple body and uniform magnetization (requires a parametric inversion)
          vertical pipe act like a pole source (generate magnetic field from a vertical pipe, carry through the analysis to get the depth of the pipe) This will serve as a template for the lab.
          compact object acts like a dipole (UXO) (a small block in a halfspace and invert to get orientation, magnitude and location)

3. Inversion (generally 3D but sometimes 2D)
          Minimal amount of text about inversion 
          Example of synthetic inversion (say a block in a half-space)

4. Applications
        geology map
        vertical pipe from TBL
        dipole (UXO)
        3D inversion (Raglan)

**Comment by fourndo** [comment]
Done over multiple PRs: #100 to #105
