### ISSUE TITLE
Magnetic Surveying on GPG:   Basic Principles (more material)

### ISSUE THREAD

**Issue by dougoldenburg** [ubcgif/gpg#78]
In the section  Basic Principles we should have extra material to mesh with items provided later.

1. For the "Source" we need to introduce the topic of time variations and the magnitude and time scales over which the changes occur. That material will be used as a base for the Processing section.

2. Need a section on Remanent Magnetism. (some combination of the slides, existing material in GPG, and the App are required.

3. Modelling magnetic fields of uniform bodies of simple shape 
       I think much of the material needed exists in the GPG.

**Comment by fourndo** [comment]
Multiple PRs for this, #84, #83 , #93 ....
